// @ts-nocheck
const { expect, test } = require("@playwright/test");

const tenantSlug = process.env.E2E_TENANT_SLUG || "asake";
const baseURL = process.env.E2E_BASE_URL || `http://${tenantSlug}.localhost:3000`;
const pageTimeout = 45000;
const renderBudgetMs = Number(process.env.E2E_RENDER_BUDGET_MS || 6000);

test.use({ storageState: process.env.E2E_STORAGE_STATE || "tests/.auth/owner.json", acceptDownloads: true });
test.setTimeout(90000);

async function expectPageReady(page, path, heading) {
  const startedAt = Date.now();
  const consoleErrors = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });
  await page.goto(`${baseURL}${path}`, { waitUntil: "domcontentloaded", timeout: pageTimeout });
  await expect(page.getByRole("heading", { name: heading })).toBeVisible({ timeout: pageTimeout });
  const elapsed = Date.now() - startedAt;
  expect(elapsed, `${path} should render inside ${renderBudgetMs}ms`).toBeLessThan(renderBudgetMs);
  expect(consoleErrors.filter((item) => !item.includes("favicon")).slice(0, 3)).toEqual([]);
}

test.describe("Owner finance production surfaces", () => {
  test("finance, payments, invoices, reports, and platform billing render within budget", async ({ page }) => {
    await expectPageReady(page, "/owner/finance", /Finance Overview/i);
    await expectPageReady(page, "/owner/payments", /^Payments$/i);
    await expectPageReady(page, "/owner/invoices", /^Invoices$/i);
    await expectPageReady(page, "/owner/reports", /^Reports$/i);
    await expectPageReady(page, "/owner/billing", /Platform Billing/i);
  });

  test("reports generate branded portrait output and export without blank print popup", async ({ page }) => {
    await page.goto(`${baseURL}/owner/reports`, { waitUntil: "domcontentloaded", timeout: pageTimeout });
    await expect(page.getByRole("heading", { name: /^Reports$/i })).toBeVisible({ timeout: pageTimeout });

    const generateButton = page.getByRole("button", { name: /Generate Report/i }).first();
    await generateButton.click();
    await expect(page.getByText(/Report generated/i).or(page.getByRole("button", { name: /Export PDF/i }))).toBeVisible({ timeout: pageTimeout });

    await page.getByRole("tab", { name: /Generated Preview/i }).click();
    const frame = page.frameLocator("iframe[title='Generated report preview']");
    await expect(frame.locator("body")).toContainText(/Generated by Roxan Education System/i, { timeout: pageTimeout });
    const html = await frame.locator("html").evaluate((node) => node.outerHTML);
    expect(html).toContain("@page{size:A4 portrait");

    const [popup] = await Promise.all([
      page.waitForEvent("popup", { timeout: pageTimeout }),
      page.getByRole("button", { name: /Export PDF/i }).click(),
    ]);
    await popup.waitForLoadState("domcontentloaded", { timeout: pageTimeout }).catch(() => {});
    await popup.waitForTimeout(800);
    await expect(popup.locator("body")).toContainText(/Generated by Roxan Education System/i);
  });

  test("platform billing invoice document downloads and prints populated portrait invoice", async ({ page }) => {
    await page.goto(`${baseURL}/owner/billing`, { waitUntil: "domcontentloaded", timeout: pageTimeout });
    await expect(page.getByRole("heading", { name: /Platform Billing/i })).toBeVisible({ timeout: pageTimeout });

    const downloadButton = page.getByRole("button", { name: /^Download$/ }).first();
    await downloadButton.waitFor({ state: "visible", timeout: pageTimeout }).catch(() => {});
    if (!(await downloadButton.isVisible().catch(() => false))) test.skip(true, "No platform invoice rows available");

    const [download] = await Promise.all([
      page.waitForEvent("download", { timeout: pageTimeout }),
      downloadButton.click(),
    ]);
    const stream = await download.createReadStream();
    const chunks = [];
    for await (const chunk of stream) chunks.push(chunk);
    const html = Buffer.concat(chunks).toString("utf8");
    expect(html).toContain("@page { size: A4 portrait;");
    expect(html).toContain("Payment instructions");
    expect(html).toMatch(/<img src="https?:\/\//);

    const [popup] = await Promise.all([
      page.waitForEvent("popup", { timeout: pageTimeout }),
      page.getByRole("button", { name: /Print \/ Save PDF/i }).first().click(),
    ]);
    await popup.waitForLoadState("domcontentloaded", { timeout: pageTimeout }).catch(() => {});
    await popup.waitForTimeout(800);
    await expect(popup.locator("body")).toContainText(/INVOICE/i);
    await expect(popup.locator("body")).toContainText(/Total due|Amount due/i);
  });

  test("student invoice detail document downloads and prints populated portrait invoice when records exist", async ({ page }) => {
    await page.goto(`${baseURL}/owner/invoices`, { waitUntil: "domcontentloaded", timeout: pageTimeout });
    await expect(page.getByRole("heading", { name: /^Invoices$/i })).toBeVisible({ timeout: pageTimeout });

    const detailButton = page.getByRole("button", { name: /View details/i }).first();
    await detailButton.waitFor({ state: "visible", timeout: pageTimeout }).catch(() => {});
    if (!(await detailButton.isVisible().catch(() => false))) test.skip(true, "No student invoice rows available");
    await detailButton.click();
    await expect(page.getByRole("button", { name: /Print \/ Save PDF/i })).toBeVisible({ timeout: pageTimeout });

    const [download] = await Promise.all([
      page.waitForEvent("download", { timeout: pageTimeout }),
      page.getByRole("button", { name: /^Download$/ }).click(),
    ]);
    const stream = await download.createReadStream();
    const chunks = [];
    for await (const chunk of stream) chunks.push(chunk);
    const html = Buffer.concat(chunks).toString("utf8");
    expect(html).toContain("@page{size:A4 portrait");
    expect(html).toContain("Bill To");

    const [popup] = await Promise.all([
      page.waitForEvent("popup", { timeout: pageTimeout }),
      page.getByRole("button", { name: /Print \/ Save PDF/i }).click(),
    ]);
    await popup.waitForLoadState("domcontentloaded", { timeout: pageTimeout }).catch(() => {});
    await popup.waitForTimeout(800);
    await expect(popup.locator("body")).toContainText(/Bill To/i);
  });
});
